# Generated by Django 2.0.1 on 2019-11-16 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='department',
            new_name='depart',
        ),
    ]
